---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-prereq
  namespace: flux-system
spec:
  path: "./10-platform/monitoring/kube-prometheus-stack/prereq"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 5m
  targetNamespace: monitoring
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-release
  namespace: flux-system
spec:
  path: "./10-platform/monitoring/kube-prometheus-stack/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 5m
  timeout: 15m
  dependsOn:
    - name: kube-prometheus-stack-prereq