apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:jS+FXKFwnhyYLCxK+M0LLB9IVwNiu/gRKBS8507TGvyglbEOmqV29L5BevvsRckA/CdSxWWKQcWfgg+58Hdoh2dtVi/zptxrErGuiB6bXgswJXPP5QvnkPm9QhCX66LX8mgkifWSRZ5MC3UEUu4x6uCLRBrTji8bJQ==,iv:woaSxZTY5C6V1rUwiBLx6+Johtaf2oC7PD9ZSEti6ZU=,tag:e4lttMduG0EntMa1QGaPdQ==,type:str]
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQmpQN3l0ekZDL01BTitX
            Q2UxM2RuUDdEN2tjRHppRzZucjFlNXJpN2xBCmcxQWk0SlhxMXRpbEZIRUhGV2lE
            eHdqQlNCLzJ4eTR6NjhoL3dTS0ZremsKLS0tIFFXTFpSL3pxdnNaYzVGaTUrNkQr
            LzFkVStGK1BIV3NrSDV1YjIrN2k2SVkKRTMm7hEEW4PmSKiEo3NSWjJytjrJiv9f
            IdcNrK1MAcOtH+KCGhNnIFO5/dvbiFA5CEBIaVuCT1iK8IaJC+5yVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T22:57:52Z"
    mac: ENC[AES256_GCM,data:YrP+rcoM1Fy+ZZ/OnlYsbwpxoGS/wIsbrpbZ3IWswcdlD/Du2y/ycKRu4KiuDXO7W17wGC+gkGBnfvXIAA3ToMxgcU53YSTXXzy3QmuNzQDYK3hLEdgPq2DryBHJ1RjNk7XIRShZ8595vmHwIFAYwhnmFT0ZNsRftaUS/9vvCgY=,iv:sPI7uUov4FrWxj0YcYeNQm1Ysfa46Uaco2xW1qAxFDM=,tag:3VUvQdgtBHV/x0+EDilwBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
