apiVersion: v1
data:
    sops: ENC[AES256_GCM,data:+V5eUwRZM2M=,iv:kJ+YqO3HGHJynJ5Ki4m849N9kJ//cYbHBTvEyGZEaA4=,tag:V+9UBtsjA+9glDg76b0qsw==,type:str]
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd1RyRFRXU2QvV2s1QWpx
            R0UyUGYxNEh1SUhlWGNwd2d5SkxnZjJTQ1NzClFGbHBFRW83WktWRExvUDhQRG9T
            R0Qxd20wd0FBVjZOR3RzTnRtYjRtcFUKLS0tIHNtUjVXakxMQjdhMStHOTVKNUdk
            SzBlWDBWU0VnQUZnaDFrcWdDanhLZkkK2D/uCsqDLBvMFkQfPht80RnmqQ6KORd1
            Cp2NO3DAoVA7aH/qttQPanwVZRtRagtXs8tt149CBYIZS7VshScnBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T21:07:15Z"
    mac: ENC[AES256_GCM,data:xGqhNQkMxSuQlk3h02WKYcw+Yz7frgQuBFmLP3pJtLxGUyNWXf30m4iHjDbMv6/9FUyLZ1uoQDImo06H3Eo0kgvsetO9iOAg6p9s+M4ZbS8om/m85zwH3lKXMiBo7zQzebdc2dHhKNTa18sWqoqo6DAn0Xo7TFuLMmPlUCzImwM=,iv:iIam77ZBxeuayUVipeC/2Xayo1YrJp1MCi04Ga2Es/A=,tag:nwwYDProQFYYlY3VGqhO9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
