apiVersion: v1
kind: Secret
metadata:
    name: discord_url
    namespace: flux-system
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:lqwtn/9LQ4ZguAOQaqohKuF3M+skO2gi2ijyeR46uGeLVIjGSxvFj7Nrhf/5vT3pC6/jEOiwdgZB5jDm+U1gji49Xl6Cfxqn9nwfnq4L8dfzf4GPj6dRqLXESPlcXsfO+al4icWaYgLzaGpUyVSzFlQ8dnzknsfmjg==,iv:TiD7B/HP1T8h5vsGLy/B91xvsx759bLuhBt9xPG0eYY=,tag:8iROnIhpEXYh72Cz6EJwPQ==,type:str]
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNzk0NG5WRXo5SkdtMjRQ
            M2VCYVZiWUEvQ2U0d3RTNTMxSU01eUlXbmlvCkZNdTRkZFVXSUdxeTZqaEZWcEpy
            OU16M09BbGJVc3JNU2NrTFJ3Q0JWcWsKLS0tIDdQcnFwRXpLdCtIWDdPYklwcisv
            OVliTWsrOE9pRHdrZzN6WWVBWC8rWFkKycOkVPcwbyT37dnRWxQPNI+S/9d3OaOR
            DQ3FJuJmc5MJQmygQFyibbI+CY0KEYVSvJqKVOd0E44zkM7lGRuH3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T21:45:05Z"
    mac: ENC[AES256_GCM,data:mLBwuGVZlfg+Uf2Gxutns99lT56g1ILiE8V/0uM0Q/G4+VypndBYovBrMXrWLUG5hY6RPgSH0GtNb+o1VNa7UcvX4m73eGsj/HYLI0wV9gt+xn+2boiJZ5nP2gY5L7L3BHZjBlhm7Xh/Jaj3NO86wrbNsLYYN3xt29I13zk/jO0=,iv:6AKPtVJrji4LfBpvZD4rae8XlV+gUtX2VxOQhHZkQx0=,tag:DuyS10zW2rCcmsdh5GbkUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
