apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:jS+FXKFwnhyYLCxK+M0LLB9IVwNiu/gRKBS8507TGvyglbEOmqV29L5BevvsRckA/CdSxWWKQcWfgg+58Hdoh2dtVi/zptxrErGuiB6bXgswJXPP5QvnkPm9QhCX66LX8mgkifWSRZ5MC3UEUu4x6uCLRBrTji8bJQ==,iv:woaSxZTY5C6V1rUwiBLx6+Johtaf2oC7PD9ZSEti6ZU=,tag:e4lttMduG0EntMa1QGaPdQ==,type:str]
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQmpQN3l0ekZDL01BTitX
            Q2UxM2RuUDdEN2tjRHppRzZucjFlNXJpN2xBCmcxQWk0SlhxMXRpbEZIRUhGV2lE
            eHdqQlNCLzJ4eTR6NjhoL3dTS0ZremsKLS0tIFFXTFpSL3pxdnNaYzVGaTUrNkQr
            LzFkVStGK1BIV3NrSDV1YjIrN2k2SVkKRTMm7hEEW4PmSKiEo3NSWjJytjrJiv9f
            IdcNrK1MAcOtH+KCGhNnIFO5/dvbiFA5CEBIaVuCT1iK8IaJC+5yVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T22:57:52Z"
    mac: ENC[AES256_GCM,data:YrP+rcoM1Fy+ZZ/OnlYsbwpxoGS/wIsbrpbZ3IWswcdlD/Du2y/ycKRu4KiuDXO7W17wGC+gkGBnfvXIAA3ToMxgcU53YSTXXzy3QmuNzQDYK3hLEdgPq2DryBHJ1RjNk7XIRShZ8595vmHwIFAYwhnmFT0ZNsRftaUS/9vvCgY=,iv:sPI7uUov4FrWxj0YcYeNQm1Ysfa46Uaco2xW1qAxFDM=,tag:3VUvQdgtBHV/x0+EDilwBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:k+XHh8niO2oKFvSUqjWUUhwChvQ=,iv:O8oDmGat5DukFQ4zQ5pHPBDN6VNoM7lGmuKufPEaycI=,tag:kRM5d5pkSz5Bctx1R3f7bQ==,type:str]
    admin-user: ENC[AES256_GCM,data:jP1UKt/GxgI=,iv:f0oQRTDL9QQHu1/d1mqqIQ/Q768Je79Yj8aqWgtgWAg=,tag:XFqvhgQiWMhn1R5svzq64g==,type:str]
    ldap-toml: null
kind: Secret
metadata:
    name: grafana-cred
    namespace: monitoring
type: Opaque
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L3ZVMkNDMXlqZnhqSjhn
            SkVPOHBhVm93MHNNVWhPaGVBNlVxWm12T0hNCjVOQ3BhWDc3aUZlSW9SblZqM3Iz
            bGduMzVZbk13a0RpcHBNU0RLSnhTeHcKLS0tIGpFajBSN0lSeGJ0cjhEVXg1b2sy
            ZVd5OEtxL05hQ1ZQVmxDRzl5eGpwWDAKIfbgDmOs+4hrhYVheeYt1Ws2y5/3HY9N
            yVBTwWrwOt/9IrHO827wjp2uUssLB3Kb1skIcDVzYwouXHINaM/KMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T14:30:11Z"
    mac: ENC[AES256_GCM,data:d0OfyCVkAOL/TJDjQkhCTSF7iPz6cfrUjilS1tve7zMBviluHxpOvCcKdOR2CVfUnkTzQVDIL0DDAhunVYxzi0BG5TROB1Yi2BhzAtrhOSpSc37W05Xv0ip4Qr8JJWltNKAoy4zZgj5T4WcXiK6hd/tmIL2wGrmbhYi4enxRnxU=,iv:lxtLgopuXYPBguGh6GyAeMG3EFNplXdSndAGQyC993s=,tag:coPm/7M78C0q81O5OYEX0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2