apiVersion: v1
stringData:
    application-token: ENC[AES256_GCM,data:EoX6+XwxGg08kc8ljF8JFjx/mv8wojvTgvfJqQwG,iv:79bjv0fWd/Zv5plkKw+/IDF4Ejqx+LiZ3gbVToWxDaI=,tag:/GfDqOGV5pGkZ8Z3fMXATQ==,type:str]
    user-token: ENC[AES256_GCM,data:+oBjsPeW8CCO961Gri3i3fMDO6M4W0M0+xZH11cw,iv:p49CHkyOtIIzZrsVCgCx7h7cLxyPvXLJC447gBZmV1A=,tag:aV0ziDMgNPfB80KNV/JHjQ==,type:str]
kind: Secret
metadata:
    labels:
        reconcile.fluxcd.io/watch: Enabled
    name: monitoring-pushover
    namespace: flux-system
type: Opaque
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpblprZ0hGcWhNUGhUeVh2
            MEVRNHhIR05pUFRMVWZwYVdhRVdTY1h6c1NNCjgycXUvL29LUjI1Wi9MamtwUnl2
            bEpiYnBRcEpsTWlWanpqZWV4dndMeXMKLS0tIFl6TGN2SkRrczI5ZnNsYWE0eFlQ
            U2FHSGdiZkFzK1BZeFo0MTFSOUFCVmsKU32uYIoS7H8De0gDiyyYfkNQbqyi0Jwi
            TiJJtD00Wk0LRoqG+mcIR3hXrEUsWDMbWCspHFz5f3titjdRs06YKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T14:34:24Z"
    mac: ENC[AES256_GCM,data:1V3N9HJN73awzrF7HBuTEdEgS/7n39HZgsZamIMIdJOHXK13EfL9aLhNGTXSBPuVexA/OFNFOMMmVzyvWKnGojiLvlZ2JcuLFUa9WOKdfr+/OsZS9aV7N357/0qui3zU7M2/awQLEDDK2OJn7/bN5oxxo1+OlggG9S30eFANiZs=,iv:3ZrfTrxxY6tww6T6ZJP0cT0jg9UQpfV6FqG7clFj8dg=,tag:2a6rJ2otqgzA+yrTSgxjtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:UACUmRkB7oZFaF10/w1IZCBs/PI=,iv:Rh7GDR10BpFq3yB513ecPyiLan3P4nUF0rPD+bCa1Hw=,tag:7LkOEjHkgYmmqkwpM0U+YA==,type:str]
    admin-user: ENC[AES256_GCM,data:xdLADLM4PhY=,iv:zw/p4xOiRe0462aW2JwoYNKfzEEm5KbYA/GQYM0dPmQ=,tag:ywLR3HTy6dECzymtc3ggYA==,type:str]
    ldap-toml: null
kind: Secret
metadata:
    name: grafana-cred
    namespace: monitoring
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUTZETDFoSE9RajhianZC
            WFhRc3VvNFlNbGZUeHN3ODNrK3VCY3owalVZCmpWTmlnM0ExbFEyL2ViaGhQT3dm
            a1lJaTdLeUcvNXBSdFlJNFZQWEhFeDQKLS0tIGx5T1NxODgrU1FaMjdVZlhZZjBV
            MHJLRC95T3BRbTkrclVsek1NLzRucjQKTGZOICWicM7dQwkOc5pVNWxAsfd74s1f
            MHgKU2LzHUEw5My6T/P+B23AHy39+tcn0DD9xQ3at97gNaKVyhOpuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T15:07:06Z"
    mac: ENC[AES256_GCM,data:fq+t1pDwMbxb0odrgnFkJdFBI7ItNOVxp0AZXvMMl3FT0lLbDhLzVEHW9upqM6z9cc7vu/ER/LEU+MVJaGP8E8/qV4zo/Zy/c+ZAbjHGpG2JxmS0QV/KD/5o6d+Nz28mr5Z8yxkKquKmVuOW0zGGIi5Cb8nIp8X14aaqzMGXDCo=,iv:xK7alUSnHPvBvnBASSednmR2kWmu6L+akOvm6Z//kXo=,tag:40gi8UqqTsyMKXQC3TZKOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2