---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: x3gallery-route
  namespace: default
spec:
  parentRefs:
    - name: cilium-external
      namespace: network
  hostnames:
    - 'test-canadium.beerus.fr'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: x3gallery
          port: 80