apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-external
  namespace: network
  annotations:
    cert-manager.io/cluster-issuer: le-prod
    lbipam.cilium.io/ips: 192.168.69.128
    gatus.home-operations.com/endpoint: |-
      client:
        dns-resolver: tcp://1.1.1.1:53
      group: external
      alerts:
        - type: pushover
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    hostname: '*.beerus.fr'
    port: 80
    protocol: HTTP
  - name: https
    hostname: '*.beerus.fr'
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: wildcard-beerus
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-internal
  namespace: network
  annotations:
    cert-manager.io/cluster-issuer: le-prod
    lbipam.cilium.io/ips: 192.168.69.129
    gatus.home-operations.com/endpoint: |-
      group: internal
      guarded: true
      ui:
        hide-hostname: true
        hide-url: true
      alerts:
        - type: pushover
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    hostname: '*.internal.beerus.fr'
    port: 80
    protocol: HTTP
  - name: https
    hostname: '*.internal.beerus.fr'
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: internal-wildcard-beerus
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-external
  namespace: network
  annotations:
    gatus.home-operations.com/enabled: "false"
spec:
  parentRefs:
    - name: cilium-external
      namespace: network
      sectionName: http
  hostnames:
    - "*.beerus.fr"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-internal
  namespace: network
  annotations:
    gatus.home-operations.com/enabled: "false"
spec:
  parentRefs:
    - name: cilium-internal
      namespace: network
      sectionName: http
  hostnames:
    - "*.internal.beerus.fr"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301