apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-external
  namespace: network
  annotations:
    cert-manager.io/cluster-issuer: le-prod
    gatus.home-operations.com/endpoint: |-
      client:
        dns-resolver: tcp://1.1.1.1:53
      group: external
spec:
  infrastructure:
      lbipam.cilium.io/ips: 192.168.69.128
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    hostname: '*.beerus.fr'
    port: 80
    protocol: HTTP
  - name: https
    hostname: '*.beerus.fr'
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: wildcard-beerus
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-internal
  namespace: network
  annotations:
    cert-manager.io/cluster-issuer: le-prod
    gatus.home-operations.com/endpoint: |-
      group: internal
      guarded: true
      ui:
        hide-hostname: true
        hide-url: true
spec:
  infrastructure:
      lbipam.cilium.io/ips: 192.168.69.129
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    hostname: '*.internal.beerus.fr'
    port: 80
    protocol: HTTP
  - name: https
    hostname: '*.internal.beerus.fr'
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: wildcard-beerus
    allowedRoutes:
      namespaces:
        from: All