apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:3yFL6kBA,iv:3atCiSFqEJHGovE6vZUSHiXk1Y+xzHKz9/gtp2BeYgc=,tag:xnTmmB9XBhC01xEQLOdjfw==,type:str]
    password: ENC[AES256_GCM,data:oaERKeJUVUW+7KmoSC9H3mEQIzY=,iv:Y2apiIPM2DMCGyw0tzmb5OOyZuMSqlbb+xa22yaznMs=,tag:C4/5KmDFc9eKuvgpC0bM0g==,type:str]
kind: Secret
metadata:
    labels:
        reconcile.fluxcd.io/watch: Enabled
    name: ygege-secret
    namespace: media
type: Opaque
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaGh0WXpOY0JaVVdYbHdl
            RWNtcFM1YmpGNTVsL0x0aWVhb3A0WUVmNVFrCmJuWHBlNFFzWFhGV25LRktrRXJB
            MWxlVTVab29aYU1OOEh3VU8wTlNZV2cKLS0tIEFEbjVhUjlISEZVZjZXSllMTlhX
            ZkdScytidEl2bE42WU40RmJPQVoyc1UKmo/HZlxDOrQ2Km6udPQsdS29CGKf9QE3
            wXMPmHJut1OYcKSrT6b1jv2aT5lZHhPGbYbkNDDlQUxo4QH2Yljo4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T00:54:49Z"
    mac: ENC[AES256_GCM,data:CYQJTUaQ+iX4k1fs30nwe3koFG8pWXDZ8GpY9TVjzNgwocLxZ9al3k/DLEff4x+uyg7cRiyXc3NM6LMpaGYyXlPnyHFp3EKzYPHFczta0gHYttJBxfnKi+jdQF1RqlwI+tnRsO6b2d68zXgVPtkFyqcWq85qB5uFb1+FUdf9pWA=,iv:0jgjDLoM5/+k5zEJ8OWFzJbY4GWl4CkiMMqt2PcPUGo=,tag:0P258ZvrfR8YSHKiyA3Wuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2