apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gatus-route
  namespace: monitoring
spec:
  hostnames:
  - meteo.internal.beerus.fr
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium-internal
    namespace: network
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: monitoring-gatus-release
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /