apiVersion: v1
stringData:
    api_key: ENC[AES256_GCM,data:htOKy5qft3Mr8IyhSmprk/dCQlimIfZI6yljZS/NhtM=,iv:CoqqC+CHAsLM+r01tyF2UUjm/hfdquXXUK8VwzlwL8I=,tag:hR6zmwPiZJBB7MwC3IQh4A==,type:str]
kind: Secret
metadata:
    labels:
        reconcile.fluxcd.io/watch: Enabled
    name: tautulli-secret
    namespace: media
type: Opaque
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VGEyVmdUOGprVWdkcExS
            UXpONFVNMTEvY3lIU3k3dkhrZGdhcGtobkZJCmh3RVZ6NXZ6a1Z5ek5SektwS2RE
            WmE3UkRkWi9adGk2Z2UxUysxeWpNblEKLS0tIFNuMUZXVUcvTXhlMXd2dkFtVHpL
            R1NTRVoydHJjV0tES0RaVjhZMDFQRjAKmYsk2XYcX0OHNsoAlali/f+eOWqEhgKA
            SOA+qh2WbYW6onFxIBfRE8SLOIB7J3LIXHoxlwrEYayCTi7rufr16g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T17:39:34Z"
    mac: ENC[AES256_GCM,data:h5wliCLWVR4xwJj5jAlr6Y3tFAcM/m8EDhv0zzwhtXC2BJ91HYWvjm0YGWMTZhWiUkhFv18mMu8DYBnB1K4wbxifqryLsb1T03/A7tBjxDQL5uuwml5p6Z+qk+nZwjxosnsjFYJ2MRt61UEJoSUV1oPjLSXQwXjtWlat5TKZ+sw=,iv:5SRCdmuUTa8OSZzBpYtfiPcxpUpJZz1QIpb9lFvZjLs=,tag:8u0zsxBwh1KdUi6yIqKwsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2