apiVersion: v1
stringData:
    api_key: ENC[AES256_GCM,data:1xO0JgNHge3l/GKHDU97bUnPlz+LlLgRg8eVYBGzr2I=,iv:dFkGDIbcJXY/3su2qkA7qJ2S/KNxr1gGmHa7bufjTHs=,tag:jrJd8NFYMe92EPpHv4T49A==,type:str]
kind: Secret
metadata:
    labels:
        reconcile.fluxcd.io/watch: Enabled
    name: bazarr-secret
    namespace: media
type: Opaque
sops:
    age:
        - recipient: age1kk6e6cphx3wm9fwdtev598pw39ymyj7cu4j7ksna0fyhxf3783js2ve88k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL05EWTJjaGZ4M2hubHJ2
            YWNWelNQZnBtSUQvSVJlMFNZcTZDd3ZIdUcwClY3bUllMFV6Q09ScEowRDZpZitn
            N29mKyszdjkzRU5LUVQ5Z29VQ3hOUWsKLS0tIFhqVHJNZUUya2ZYd3VIVFJVaW9t
            UmExNlArWG5SdFFCWWovSk5HTWk1S00K9G32Yfg5SqhEECQjJdeV4+8GNZFLqOvh
            gtLBIjm4tp0QHCxsfOGEZgCbllrM2lGUg43OCRM02q/iZ80axipRaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T16:55:15Z"
    mac: ENC[AES256_GCM,data:QAN5PLTptrsDvCsRCDEzWkgvZjE0iolK8ThomzLQ5pGVA8HSft0uca/puCW8ZbrKWcqEc3xpjjRejFW40Bs/W5rAstDIJIkMP5cXYPcuxwl+0TS2++bGE/qxutaiwXxK1fMY7rYAGLJEPK/WeVGLCrExVGetOJDPtG5Ca8nJd9Y=,iv:B219O5MS/7OuKJOsB7OxUAbNIdODVPbmuqcYSQvfg8k=,tag:tFBgWjL+Wo27t5GEM8lWdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
