apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./ygege/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./seerr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./notifiarr/ks.yaml